# Spring ActiveMQ Configuration
spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true
    pool:
      enabled: false

  jms:
    listener:
      acknowledge-mode: auto
      recovery-interval: 1000 # Interval (in ms) between reconnect attempts to avoid long retries during shutdown

# Custom application properties for queue names
activemq:
  queues:
    order-queue: orders.queue
